### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by tinseltunes** [bossmansl/WLED#1]
Hi. Not an issue but a question.
I'm interested in using this new version when it goes final to power up my Megatree in my Christmas display.
Last year I used normal WLED to power up 1184 leds and for the most part everything was fine, except on fast patterns there was some lag. I put it down to the D1 Mini not being able to process that amount of data as one channel.

My question is if I split the tree up to 3 or 4 segments and using this new code, do you think it will improve the performance as it won't need to push all the data through one pin?
Note: The router is only 2 meters away from the controllers so I don't think the distance between them would be the cause of the lag.

Thanks in advance.
Duane

**Comment by bossmansl** [comment]
Hi Duane.
There have been many improvements in the memory usage within the code, which is hoped to increase the frame rate to around the 40fps mark. This can be seen now in the info tab as well as the memory usage. Obviously the 8266 chooser is not as fast as an esp32 used in dig-quad. It might be worth considering upgrading to one of them and have 4 dedicated data outputs.


> Hi. Not an issue but a question.
> I'm interested in using this new version when it goes final to power up my Megatree in my Christmas display.
> Last year I used normal WLED to power up 1184 leds and for the most part everything was fine, except on fast patterns there was some lag. I put it down to the D1 Mini not being able to process that amount of data as one channel.
> 
> My question is if I split the tree up to 3 or 4 segments and using this new code, do you think it will improve the performance as it won't need to push all the data through one pin?
> Note: The router is only 2 meters away from the controllers so I don't think the distance between them would be the cause of the lag.
> 
> Thanks in advance.
> Duane
